obj-m += rsmc_driver.o
rsmc_driver-y :=
rsmc_driver-y += rsmc_chiptype_select.o
rsmc_driver-y += x801/rsmc_start_x801.o
rsmc_driver-y += x801/rsmc_msg_loop_x801.o
rsmc_driver-y += x801/rsmc_spi_x801.o
rsmc_driver-y += x801/rsmc_device_x801.o